---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
  labels:
    chart: sealed-secrets
  annotations:
    flux.weave.works/automated: 'true'
spec:
  chartGitPath: sealed-secrets
  releaseName: sealed-secrets
  values:
    image: quay.io/bitnami/sealed-secrets-controller:v0.7.0
    service:
      type: NodePort
